---
kind: pipeline
type: docker
name: test-pr

platform:
  os: linux
  arch: amd64

steps:
- name: identify-runner
  image: alpine:3.14.2
  commands:
  - echo $DRONE_RUNNER_NAME

- name: initialize
  image: grafana/build-container:1.4.2
  commands:
  - mkdir -p bin
  - curl -fL -o bin/grabpl https://grafana-downloads.storage.googleapis.com/grafana-build-pipeline/v2.4.6/grabpl
  - chmod +x bin/grabpl
  - ./bin/grabpl verify-drone
  - curl -fLO https://github.com/jwilder/dockerize/releases/download/v$${DOCKERIZE_VERSION}/dockerize-linux-amd64-v$${DOCKERIZE_VERSION}.tar.gz
  - tar -C bin -xzvf dockerize-linux-amd64-v$${DOCKERIZE_VERSION}.tar.gz
  - rm dockerize-linux-amd64-v$${DOCKERIZE_VERSION}.tar.gz
  - yarn install --frozen-lockfile --no-progress
  environment:
    DOCKERIZE_VERSION: 0.6.1

- name: codespell
  image: grafana/build-container:1.4.2
  commands:
  - "echo -e \"unknwon\nreferer\nerrorstring\neror\niam\nwan\" > words_to_ignore.txt"
  - codespell -I words_to_ignore.txt docs/
  depends_on:
  - initialize

- name: shellcheck
  image: grafana/build-container:1.4.2
  commands:
  - ./bin/grabpl shellcheck
  depends_on:
  - initialize

- name: restore-cache
  pull: always
  image: homerovalle/drone-gcs-cache
  settings:
    bucket: test-julien
    restore: true
  environment:
    GCS_CACHE_JSON_KEY:
      from_secret: tf_google_credentials
  depends_on:
  - initialize

- name: lint-backend
  image: grafana/build-container:1.4.2
  commands:
  - make gen-go
  - ./bin/grabpl lint-backend --edition oss
  environment:
    CGO_ENABLED: 1
  depends_on:
  - restore-cache

- name: test-frontend
  image: grafana/build-container:1.4.2
  commands:
  - yarn cache list
  - yarn run ci:test-frontend
  environment:
    TEST_MAX_WORKERS: 50%
  depends_on:
  - lint-backend

- name: build-frontend
  image: grafana/build-container:1.4.2
  commands:
  - ./bin/grabpl build-frontend --jobs 8 --no-install-deps --edition oss --build-id ${DRONE_BUILD_NUMBER} --no-pull-enterprise
  depends_on:
  - lint-backend

- name: rebuild-cache
  pull: always
  image: homerovalle/drone-gcs-cache
  settings:
    bucket: test-julien
    mount:
    - /opt/drone/yarncache
    rebuild: true
  environment:
    GCS_CACHE_JSON_KEY:
      from_secret: tf_google_credentials
  when:
    event:
    - pull_request
  depends_on:
  - build-frontend

node:
  type: no-parallel

trigger:
  event:
  - pull_request

---
kind: secret
name: dockerconfigjson

get:
  path: secret/data/common/gcr
  name: .dockerconfigjson

---
kind: secret
name: github_token

get:
  path: infra/data/ci/github/grafanabot
  name: pat

---
kind: secret
name: drone_token

get:
  path: infra/data/ci/drone
  name: machine-user-token

---
kind: secret
name: tf_google_credentials

get:
  path: infra/data/ci/terraform/google
  name: credentials.json

---
kind: secret
name: access_key

get:
  path: infra/data/ci/test-drone-caching
  name: access-key

---
kind: secret
name: secret

get:
  path: infra/data/ci/test-drone-caching
  name: secret

---
kind: signature
hmac: 306d7503989ac01d2bc130bb2a64baa954b0192cf61297d6cfd22cccc82377dc

...
