---
depends_on: []
kind: pipeline
name: test-pr
node:
  type: no-parallel
platform:
  arch: amd64
  os: linux
services: null
steps:
- depends_on:
  - clone
  image: jduchesnegrafana/drone-cache:v1.2.0-rc0-dirtytest
  name: restore-cache
  pull: always
  settings:
    backend: gcs
    bucket: test-julien
    cache_key: test123
    json_key:
      from_secret: tf_google_credentials
    mount:
    - yarncache
    - node_modules
    restore: "true"
- commands:
  - echo $DRONE_RUNNER_NAME
  image: alpine:3.14.2
  name: identify-runner
- commands:
  - echo test
  - mkdir -p bin
  - curl -fL -o bin/grabpl https://grafana-downloads.storage.googleapis.com/grafana-build-pipeline/v2.5.2/grabpl
  - chmod +x bin/grabpl
  - ./bin/grabpl verify-drone
  - make gen-go
  - ls -a yarncache
  - yarn install --immutable
  depends_on:
  - restore-cache
  environment:
    YARN_CACHE_FOLDER: /drone/src/yarncache
  image: grafana/build-container:1.4.3
  name: initialize
- commands:
  - |-
    echo -e "unknwon
    referer
    errorstring
    eror
    iam
    wan" > words_to_ignore.txt
  - codespell -I words_to_ignore.txt docs/
  - rm words_to_ignore.txt
  depends_on:
  - initialize
  image: grafana/build-container:1.4.3
  name: codespell
- commands:
  - ./bin/grabpl shellcheck
  depends_on:
  - initialize
  image: grafana/build-container:1.4.3
  name: shellcheck
- commands:
  - ./bin/grabpl lint-backend --edition oss
  depends_on:
  - initialize
  environment:
    CGO_ENABLED: "1"
  image: grafana/build-container:1.4.3
  name: lint-backend
- commands:
  - yarn run ci:test-frontend
  depends_on:
  - restore-cache
  - initialize
  environment:
    TEST_MAX_WORKERS: 50%
    YARN_CACHE_FOLDER: /drone/src/yarncache
  image: grafana/build-container:1.4.3
  name: test-frontend
- commands:
  - ./bin/grabpl build-frontend --jobs 8 --no-install-deps --edition oss --build-id
    ${DRONE_BUILD_NUMBER} --no-pull-enterprise
  depends_on:
  - test-frontend
  environment:
    YARN_CACHE_FOLDER: /drone/src/yarncache
  image: grafana/build-container:1.4.3
  name: build-frontend
- depends_on:
  - initialize
  image: jduchesnegrafana/drone-cache:v1.2.0-rc0-dirtytest
  name: rebuild-cache
  pull: always
  settings:
    backend: gcs
    bucket: test-julien
    cache_key: test123
    json_key:
      from_secret: tf_google_credentials
    mount:
    - yarncache
    - node_modules
    rebuild: "true"
  when:
    event: pull_request
trigger:
  event:
  - pull_request
type: docker
---
get:
  name: .dockerconfigjson
  path: secret/data/common/gcr
kind: secret
name: dockerconfigjson
---
get:
  name: pat
  path: infra/data/ci/github/grafanabot
kind: secret
name: github_token
---
get:
  name: machine-user-token
  path: infra/data/ci/drone
kind: secret
name: drone_token
---
get:
  name: credentials.json
  path: infra/data/ci/terraform/google
kind: secret
name: tf_google_credentials
---
get:
  name: access-key
  path: infra/data/ci/test-drone-caching
kind: secret
name: access_key
---
get:
  name: secret
  path: infra/data/ci/test-drone-caching
kind: secret
name: secret
---
kind: signature
hmac: 619af5ab5be3702dd084d32a1c2fb457cdf024a9c980b24722a7b5a04c510800

...
