name: Levitate (detect)

on: pull_request

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Add "announcement" label
      uses: actions/github-script@v5
      env:
        PR_NUMBER: ${{ github.event.number }}
      with:
        script: |
          github.rest.issues.addLabels({
            issue_number: process.env.PR_NUMBER,
            owner: context.repo.owner,
            repo: context.repo.repo,
            labels: ['announcement']
          })

    # - name: Install Node.js
    #   uses: actions/setup-node@v2
    #   with:
    #     node-version: '16'

    # - name: Install Yarn
    #   run: npm install --global yarn

    # - name: Get link for the Github Action job
    #   id: job
    #   uses: actions/github-script@v5
    #   with:
    #     script: |
    #         const script = require('./.github/workflows/scripts/pr-get-job-link.js')
    #         await script({github, context, core})
      
    # - name: Install dependencies
    #   run: yarn install --immutable

    # - name: Build packages
    #   run: yarn packages:build

    # - name: Detect breaking changes
    #   id: breaking-changes
    #   run: ./scripts/check-breaking-changes.sh 
    #   env:
    #     FORCE_COLOR: 3
    #     GITHUB_JOB_LINK: ${{steps.job.outputs.link}}
    #     GITHUB_STEP_NUMBER: 7

    # - name: Persisting the check output
    #   run: |
    #       mkdir -p ./pr
    #       echo "{ \"exit_code\": ${{ steps.breaking-changes.outputs.is_breaking }}, \"message\": \"${{ steps.breaking-changes.outputs.mesage }}\", \"pr_number\": "${{ github.event.number }}" }" > ./pr/result.json

    # - name: Upload check output as artifact
    #   uses: actions/upload-artifact@v2
    #   with:
    #     name: pr
    #     path: pr/
