name: Levitate (notify)

# read-write repo token
# access to secrets
on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Levitate (detect)"]
    types:
      - completed

jobs:
  notify:
    name: Notify
    runs-on: ubuntu-latest
    # if: >
    #   ${{ github.event.workflow_run.event == 'pull_request' &&
    #   github.event.workflow_run.conclusion == 'success' }}

    steps:
    - name: Debugging
      uses: actions/github-script@v3.1.0
      with:
        script: |
          console.log(JSON.stringify({
            workflow_run_event: "${{github.event.workflow_run.event }}",
            workflow_run_conclusion: "${{github.event.workflow_run.conclusion }}",
            workflow_run_id: ${{github.event.workflow_run.id }},
            workflow_run_url: "${{github.event.workflow_run.url }}",
          }, null, 4));

    # - name: Comment on PR
    #   if: ${{ steps.breaking-changes.outputs.is_breaking == 1 }}
    #   uses: marocchino/sticky-pull-request-comment@v2
    #   with:
    #     number: ${{ github.event.number }}
    #     message: |
    #       ⚠️ &nbsp;&nbsp;**Possible breaking changes**

    #       _(Open the links below in a new tab to go to the correct steps)_

    #       ${{ steps.breaking-changes.outputs.message }}

    #       [Check console output](${{steps.get-job-link.outputs.result}})

    # - name: Remove comment on PR
    #   if: ${{ steps.breaking-changes.outputs.is_breaking == 0 }}
    #   uses: marocchino/sticky-pull-request-comment@v2
    #   with:
    #     number: ${{ github.event.number }}
    #     delete: true


    # - name: Add "breaking change" label
    #   if: ${{ steps.breaking-changes.outputs.is_breaking == 1 && steps.does-label-exist.outputs.result == 0 }}
    #   uses: actions/github-script@v5
    #   env:
    #     PR_NUMBER: ${{ github.event.number }}
    #   with:
    #     script: |
    #       github.rest.issues.addLabels({
    #         issue_number: process.env.PR_NUMBER,
    #         owner: context.repo.owner,
    #         repo: context.repo.repo,
    #         labels: ['breaking change']
    #       })

    # - name: Remove "breaking change" label
    #   if: ${{ steps.breaking-changes.outputs.is_breaking == 0 && steps.does-label-exist.outputs.result == 1 }}
    #   uses: actions/github-script@v5
    #   env:
    #     PR_NUMBER: ${{ github.event.number }}
    #   with:
    #     script: |
    #       github.rest.issues.removeLabel({
    #         issue_number: process.env.PR_NUMBER,
    #         owner: context.repo.owner,
    #         repo: context.repo.repo,
    #         name: 'breaking change'
    #       })

    # # This is very weird, the actual request goes through (comes back with a 201), but does not assign the team.
    # # Related issue: https://github.com/renovatebot/renovate/issues/1908
    # - name: Add "grafana/plugins-platform-frontend" as a reviewer
    #   if: ${{ steps.breaking-changes.outputs.is_breaking == 1 }}
    #   uses: actions/github-script@v5
    #   env:
    #     PR_NUMBER: ${{ steps.finder.outputs.pr }}
    #   with:
    #     script: |
    #       const response = await github.rest.pulls.requestReviewers({
    #         pull_number: process.env.PR_NUMBER,
    #         owner: context.repo.owner,
    #         repo: context.repo.repo,
    #         reviewers: [],
    #         team_reviewers: ['grafana/plugins-platform-frontend']
    #       })

    #       console.log(response)

    # - name: Remove "grafana/plugins-platform-frontend" from the list of reviewers
    #   if: ${{ steps.breaking-changes.outputs.is_breaking == 0 }}
    #   uses: actions/github-script@v5
    #   env:
    #     PR_NUMBER: ${{ steps.finder.outputs.pr }}
    #   with:
    #     script: |
    #       const response = await github.rest.pulls.removeRequestedReviewers({
    #         pull_number: process.env.PR_NUMBER,
    #         owner: context.repo.owner,
    #         repo: context.repo.repo,
    #         reviewers: [],
    #         team_reviewers: ['grafana/plugins-platform-frontend']
    #       })

    #       console.log(response)

    # - name: Exit
    #   run: exit ${{ steps.breaking-changes.outputs.is_breaking }}
    #   shell: bash

